spring.application.name=link-shortening-service

server.port=8080

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://postgres:5432/link_shortening_db
spring.liquibase.user=postgres
spring.liquibase.password=postgresql

logging.level.org.springframework.r2dbc.core=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG